LIBRARY     ROTKNOB
DESCRIPTION 'Dialog Control Library /RotationKnob/'
EXETYPE     NT
VERSION     1.0
CODE        PRELOAD MOVEABLE DISCARDABLE
DATA        PRELOAD MOVEABLE SINGLE
HEAPSIZE    1024
EXPORTS     RotKnobInfo    @2
            RotKnobStyle   @3
            RotKnobFlags   @4
            RotKnobWndFn   @5
            RotKnobDlgFn   @6
            RotKnobInfoRW  @7
            RotKnobFlagsRW @8
            ListClasses    @9 RESIDENTNAME
