#include <time.h>
#include <memory.h>
#include <stdarg.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <math.h>
#include <windows.h>
#include <commdlg.h>
#ifdef WIN95
#include <commctrl.h>
#endif
#ifndef WIN32
#include <ntdefs.h>
#endif
#include <manager.hpp>
#include <drwtools.hpp>
#include <dispdev.hpp>
#include <window.hpp>
#include <metadev.hpp>
#include <dialog.hpp>
#include <control.hpp>
#include <simpdlg.hpp>
#include <printer.hpp>
#include <defines.h>

#include "editor.h"
#include "editdlgs.hpp"
#include "editor.hpp"
