/*
    editor.h - ID codes for edit program and resource file.
*/

#define IDD_NOTFOUND_DIALOG    1001
#define IDD_FIND_DIALOG        1002
#define IDD_REPLACE_DIALOG     1003
#define IDD_QUERY_DIALOG       1004
#define IDD_SPECINS_DIALOG     1005
#define IDD_COMMAND_DIALOG     1006

#define IDM_GOLD_KEY		517
#define IDM_DEL_LINE		528
#define IDM_DEL_WORD		529
#define IDM_HELP		530
#define IDM_MARK		531

#define IDM_DUMMY		550
#define IDM_BACK		551
#define IDM_QUICK_EXIT		552

#define IDM_BEGIN		700
#define IDM_END			701
#define IDM_SAVE		702
#define IDM_PRINT		703
#define IDM_PASTE		704
#define IDM_OPEN		705
#define IDM_NEW			706
#define IDM_ABOUT		707
#define IDM_EXIT		708
#define IDM_FIND		709
#define IDM_REPLACE		710
#define IDM_SAVE_EXIT		711
#define IDM_SAVE_AS		712
#define IDM_FIND_NEXT		713
#define IDM_SELECT		714
#define IDM_PRINT_SETUP		715
#define IDM_CUT			716
#define IDM_COPY		717
#define IDM_HOME		718
#define IDM_CLEAR		719

#define IDC_FIND_EDIT           801
#define IDC_REPLACE_EDIT        802
#define IDC_MATCH_CASE          803
#define IDC_REPLACE_ALL         805
#define IDC_QUERY               806
#define IDC_MSG_TEXT            808
#define IDC_TEXT                201
#define IDC_EDIT                202

#define IDC_OKAY                999

#define ID_TOOLBAR		1998
#define IDB_TOOLBAR		1999
